# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: build

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /toolcache/android-sdk
      FDROID_JKS: /toolcache/android-jks/fdroid.jks
      GRADLE_USER_HOME: /toolcache/gradle
    steps:
    - uses: actions/checkout@v3

    - name: assemble fdroid
      run: |
        bash ./gradlew --no-daemon assembleFdroid \
          -PFDROID_STORE_FILE=${FDROID_JKS} \
          -PFDROID_STORE_PASSWORD=${{ secrets.FDROID_STORE_PASSWORD }} \
          -PFDROID_KEY_ALIAS=fdroid \
          -PFDROID_KEY_PASSWORD=${{ secrets.FDROID_KEY_PASSWORD }}

    - name: prepare ssh
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.APK_DEPLOY_SSH_KEY }}" | tr -d \\r > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: deploy apks
      run: |
        find . -name '*.apk' -type f | while read APK; do
          scp -oStrictHostKeyChecking=no $APK ${{ secrets.APK_DEPLOY_USER }}@${{ secrets.APK_DEPLOY_HOST }}:fdroid/repo/
        done

        ssh -oStrictHostKeyChecking=no ${{ secrets.APK_DEPLOY_USER }}@${{ secrets.APK_DEPLOY_HOST }} sudo -u docker-mgr /usr/local/sbin/fdroid-update-repo
